development:
  adapter: mysql2
  database: test
  pool: 5
  timeout: 5000
  host: '127.0.0.1'
  port: 3306
  password: 
  username: root

test:
  adapter: mysql2
  database: test
  pool: 5
  timeout: 5000
  port: 3306

production:
  adapter: mysql2
  database: db/production.mysql2
  pool: 5
  timeout: 5000
  port: 3306